
name: VAR

on:
  push:
  workflow_dispatch:

jobs:

  variable:
    name: variable
    if: ${{ vars.UPLOAD_PACKAGES == 'FALSE' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
